### ISSUE TITLE
Implement Google Maps Static API

### ISSUE THREAD

**Issue by Mike-Diaz** [angelicrf/thumbtack#11]
The Maps Static API lets you embed a Google Maps image on your web page without requiring JavaScript or any dynamic page loading. The Maps Static API service creates your map based on URL parameters sent through a standard HTTP request and returns the map as an image you can display on your web page.

https://developers.google.com/maps/documentation/maps-static/intro

**Comment by austins** [comment]
Use Geocoding API to convert coordinates to an approximate address: https://developers.google.com/maps/documentation/geocoding/
