### ISSUE TITLE
Look over: test and make sure everything works and looks good

### ISSUE THREAD

**Issue by austins** [angelicrf/thumbtack#22]
**When we have finished implementing our features and are in the last week of the project**, make sure everything works and looks good.

Make sure all main features and views (pages) work on Android. Good things to look at:
- UI looks good
- Locations
- New Location
- Edit Location
- Map features
- Saving to DB
- Fix any grammatical issues and typos

**Comment by angelicrf** [comment]
I’d recommend to take out ‘route’ from the locations component as a props since we never used it.

**Comment by austins** [comment]
@angelicrf, not a huge concern right now, but good point. Let's not close this issue yet until everyone has said the app works well for them and looks good. I know @Mike-Diaz and you have already ran the latest code and seem to be ok with the current app. I would like @Silicob's ok with the current app.

**Comment by Silicob** [comment]
This looks good to me.
