### ISSUE TITLE
Final presentation

### ISSUE THREAD

**Issue by Silicob** [angelicrf/thumbtack#25]
I am willing to present. Anyone else?

**Comment by austins** [comment]
We all have to be there, so we'll all be speaking.

**Comment by Silicob** [comment]
@austins would you like to assign topics for us to present?

**Comment by austins** [comment]
@Silicob, it's informal so I can mention people's names if they wish to speak about a certain thing we may be demoing.

**Comment by austins** [comment]
Good job, everyone!
